version: "3.9"
name: laravel-app-e2e-test

volumes:
  logs-data:

networks:
  database:
  tester:
  jaeger-net:

services:
  app:
    build:
      context: .
      dockerfile: app-e2e.dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OTEL_PHP_AUTOLOAD_ENABLED: true
      OTEL_SERVICE_NAME: my-laravel-app
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
    networks:
      database:
      tester:
      jaeger-net:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/up"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - "logs-data:/app/storage/logs/"
  app-e2e-tester:
    build:
      context: .
      dockerfile: app-e2e-tester.dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
      app:
        condition: service_healthy
    environment:
      APP_E2E_TEST_URL: http://app:8000
      APP_E2E_TEST_LOG_PATH: /app/storage/logs/laravel.log
      CI_SKIP: ${CI_SKIP}
    networks:
      tester:
    volumes:
      - "./allure-results:/app/allure-results"
      - "logs-data:/app/storage/logs/"
  postgres-db:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 3s
    networks:
      database:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - jaeger-net
  collector:
    image: otel/opentelemetry-collector
    #    ports:
    #      - "4318:4318"
    volumes:
      - "./otel-collector-config.yaml:/etc/otelcol/config.yaml"
      - "./otel-traces.json:/var/logs/otel-traces.json"
    networks:
      - jaeger-net
