version: "3.9"
name: laravel-app-jaeger

networks:
  jaeger:

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - jaeger
  collector:
    image: otel/opentelemetry-collector
    ports:
      - "4318:4318"
    volumes:
      -  "./otel-collector-config.yaml:/etc/otelcol/config.yaml"
      -  "./otel-traces.json:/var/logs/otel-traces.json"
    networks:
      - jaeger
