version: "3.9"
name: laravel-app-swoole

networks:
  monitoring:
  redis-net:
  exporter-net:
  k6:

volumes:
  redis-data:
  influxdb-data:

services:
  app:
    deploy:
      resources:
        limits:
          memory: 4gb
          cpus: "4"
    build:
      context: .
      dockerfile: php-octane-swoole.dockerfile
    environment:
      APP_URL: ${APP_URL}
      APP_KEY: ${APP_KEY}
      APP_ENV: production
      APP_DEBUG: false
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
    ports:
      - "8101:8000"
    networks:
      - redis-net
      - monitoring
      - k6
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-octane.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.listen-address=:9090"
    ports:
      - "9090:9090"
    networks:
      - monitoring
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - redis-net
  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - monitoring
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - ./load-data/provisioning-octane:/etc/grafana/provisioning
      - ./load-data/dashboards-octane:/var/lib/grafana/dashboards
  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - monitoring
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_HTTP_BIND_ADDRESS=:8096
    volumes:
      - influxdb-data:/var/lib/influxdb
  k6:
    image: grafana/k6:latest
    depends_on:
      - app
    networks:
      - k6
    #    ports:
    #      - "6567:6567"
    environment:
      - K6_OUT=influxdb=http://influxdb:8096/k6
    volumes:
      - ./k6-octane.js:/scripts/k6.js
    command: run /scripts/k6.js
