receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: ":4318"

exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  file:
    path: "/traces/otel-traces.json"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, file]
