receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: ":4318"
        cors:
          allowed_origins:

exporters:
  otlp:
    endpoint: "http://jaeger:14268/api/traces"
    tls:
      insecure: true
  file:
    path: "/var/logs/otel-traces.json"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp, file]
    metrics:
      receivers: [otlp]
      exporters: [otlp]
